//! Generation entry point. Iteration 1 of Phase 0: emit a buildable
//! flat clap CLI crate. No HTTP calls yet; subcommand handlers print a
//! TODO line so the user can see arg parsing works. Subsequent
//! iterations layer in models, real reqwest calls, type fidelity.

use forge_plugin_sdk::ir::{Body, Ir, Operation, Parameter};
use forge_plugin_sdk::{GenerationOutput, OutputFile};

use crate::config::Config;
use crate::naming::{kebab_case, pascal_case, snake_case};

pub fn all(ir: &Ir, cfg: &Config) -> GenerationOutput {
    let bin_name = bin_name(ir, cfg);
    let pkg_name = format!("{bin_name}-cli");

    let cargo_toml = emit_cargo_toml(&pkg_name, &bin_name);
    let main_rs = emit_main_rs(ir, cfg, &bin_name);
    let readme = emit_readme(ir, &bin_name);

    GenerationOutput {
        files: vec![
            OutputFile::text("Cargo.toml", cargo_toml),
            OutputFile::text("src/main.rs", main_rs),
            OutputFile::text("README.md", readme),
        ],
        diagnostics: vec![],
    }
}

fn bin_name(ir: &Ir, cfg: &Config) -> String {
    if let Some(n) = cfg.name.as_deref().filter(|s| !s.is_empty()) {
        return kebab_case(n);
    }
    let title = ir.info.title.trim();
    if title.is_empty() {
        "api-cli".into()
    } else {
        kebab_case(title)
    }
}

fn default_base_url(ir: &Ir, cfg: &Config) -> String {
    if let Some(u) = cfg.base_url.as_deref().filter(|s| !s.is_empty()) {
        return u.to_string();
    }
    ir.servers
        .first()
        .map(|s| s.url.clone())
        .unwrap_or_else(|| "http://localhost".into())
}

fn emit_cargo_toml(pkg_name: &str, bin_name: &str) -> String {
    format!(
        r#"# Generated by openapi-forge / generator-rust-clap.
[package]
name = "{pkg_name}"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "{bin_name}"
path = "src/main.rs"

[dependencies]
clap = {{ version = "4", features = ["derive", "env"] }}
tokio = {{ version = "1", features = ["macros", "rt-multi-thread"] }}
serde = {{ version = "1", features = ["derive"] }}
serde_json = "1"
anyhow = "1"
"#
    )
}

fn emit_main_rs(ir: &Ir, cfg: &Config, bin_name: &str) -> String {
    let title = escape_rust_string(&ir.info.title);
    let version = escape_rust_string(&ir.info.version);
    let base_url = escape_rust_string(&default_base_url(ir, cfg));

    let mut out = String::new();
    out.push_str("// Generated by openapi-forge / generator-rust-clap; do not edit by hand.\n\n");
    out.push_str("use clap::{Parser, Subcommand};\n\n");

    out.push_str(&format!(
        "#[derive(Parser)]\n#[command(name = \"{bin_name}\", version = \"{version}\", about = \"{title}\", long_about = None)]\nstruct Cli {{\n    /// API base URL.\n    #[arg(long, global = true, default_value = \"{base_url}\")]\n    base_url: String,\n\n    #[command(subcommand)]\n    cmd: Cmd,\n}}\n\n"
    ));

    if ir.operations.is_empty() {
        out.push_str("#[derive(Subcommand)]\nenum Cmd {\n    /// (No operations declared in the spec.)\n    #[command(hide = true)]\n    Noop,\n}\n\n");
    } else {
        out.push_str("#[derive(Subcommand)]\nenum Cmd {\n");
        for op in &ir.operations {
            out.push_str(&render_variant(op));
        }
        out.push_str("}\n\n");
    }

    out.push_str("#[tokio::main(flavor = \"multi_thread\")]\nasync fn main() -> anyhow::Result<()> {\n    let cli = Cli::parse();\n    match cli.cmd {\n");
    if ir.operations.is_empty() {
        out.push_str("        Cmd::Noop => {}\n");
    } else {
        for op in &ir.operations {
            out.push_str(&render_match_arm(op));
        }
    }
    out.push_str("    }\n    Ok(())\n}\n");

    out
}

fn render_variant(op: &Operation) -> String {
    let variant = pascal_case(&op.id);
    let summary = first_line(op.documentation.as_deref()).unwrap_or_default();
    let mut s = String::new();
    if !summary.is_empty() {
        s.push_str(&format!("    /// {}\n", escape_doc(&summary)));
    }

    let fields = collect_fields(op);
    if fields.is_empty() {
        s.push_str(&format!("    {variant},\n"));
    } else {
        s.push_str(&format!("    {variant} {{\n"));
        for f in &fields {
            if let Some(doc) = &f.doc {
                s.push_str(&format!("        /// {}\n", escape_doc(doc)));
            }
            for attr in &f.attrs {
                s.push_str(&format!("        {attr}\n"));
            }
            s.push_str(&format!("        {}: {},\n", f.ident, f.ty));
        }
        s.push_str("    },\n");
    }
    s
}

fn render_match_arm(op: &Operation) -> String {
    let variant = pascal_case(&op.id);
    let fields = collect_fields(op);
    let mut s = String::new();
    if fields.is_empty() {
        s.push_str(&format!(
            "        Cmd::{variant} => {{ eprintln!(\"TODO: call {} with base_url={{}}\", cli.base_url); }}\n",
            op.id
        ));
    } else {
        let names: Vec<&str> = fields.iter().map(|f| f.ident.as_str()).collect();
        s.push_str(&format!(
            "        Cmd::{variant} {{ {} }} => {{ eprintln!(\"TODO: call {} base_url={{}} args={{:?}}\", cli.base_url, ({},)); }}\n",
            names.join(", "),
            op.id,
            names.join(", "),
        ));
    }
    s
}

struct Field {
    ident: String,
    ty: String,
    doc: Option<String>,
    attrs: Vec<String>,
}

fn collect_fields(op: &Operation) -> Vec<Field> {
    let mut out = Vec::new();
    // Path params: positional, required (always required per OAS).
    for p in &op.path_params {
        out.push(field_for_param(p, FieldKind::Positional));
    }
    // Query/header/cookie: long flags.
    for p in &op.query_params {
        out.push(field_for_param(p, FieldKind::Flag));
    }
    for p in &op.header_params {
        out.push(field_for_param(p, FieldKind::Flag));
    }
    for p in &op.cookie_params {
        out.push(field_for_param(p, FieldKind::Flag));
    }
    // Body: --body flag accepting inline JSON, @file, or - for stdin.
    if let Some(body) = &op.request_body {
        out.push(field_for_body(body));
    }
    out
}

#[derive(Copy, Clone)]
enum FieldKind {
    Positional,
    Flag,
}

fn field_for_param(p: &Parameter, kind: FieldKind) -> Field {
    let ident = snake_case(&p.name);
    let (ty, attrs) = match (kind, p.required) {
        (FieldKind::Positional, _) => ("String".to_string(), vec![]),
        (FieldKind::Flag, true) => (
            "String".to_string(),
            vec![format!("#[arg(long = \"{}\")]", kebab_case(&p.name))],
        ),
        (FieldKind::Flag, false) => (
            "Option<String>".to_string(),
            vec![format!("#[arg(long = \"{}\")]", kebab_case(&p.name))],
        ),
    };
    let doc = first_line(p.documentation.as_deref());
    Field { ident, ty, doc, attrs }
}

fn field_for_body(body: &Body) -> Field {
    let ty = if body.required { "String" } else { "Option<String>" };
    Field {
        ident: "body".into(),
        ty: ty.into(),
        doc: Some("Request body: inline JSON, @file.json, or - for stdin.".into()),
        attrs: vec!["#[arg(long = \"body\")]".into()],
    }
}

fn emit_readme(ir: &Ir, bin_name: &str) -> String {
    format!(
        "# {bin}\n\nGenerated by openapi-forge / generator-rust-clap.\n\nSpec: {title} v{version}\n\nOperations: {n}\n\n## Build\n\n```sh\ncargo build --release\n```\n\n## Status\n\nIteration 1 of Phase 0: argument parsing only. Subcommand handlers\nprint a TODO line; real HTTP calls land in a future iteration.\n",
        bin = bin_name,
        title = ir.info.title,
        version = ir.info.version,
        n = ir.operations.len(),
    )
}

fn first_line(s: Option<&str>) -> Option<String> {
    s.and_then(|s| s.lines().next()).map(|l| l.trim().to_string()).filter(|s| !s.is_empty())
}

fn escape_rust_string(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

fn escape_doc(s: &str) -> String {
    s.replace('\\', "\\\\").replace('\r', "")
}
