//! Generation entry point. Phase 0 iteration 2: emit a buildable flat
//! clap CLI crate that makes real HTTP calls via reqwest. Inputs and
//! outputs travel as `serde_json::Value` for now — type fidelity for
//! params and full model emission are followups.

use forge_plugin_sdk::ir::{Body, HttpMethod, Ir, Operation, Parameter};
use forge_plugin_sdk::{GenerationOutput, OutputFile};

use crate::config::Config;
use crate::naming::{kebab_case, pascal_case, screaming_snake, snake_case};

pub fn all(ir: &Ir, cfg: &Config) -> GenerationOutput {
    let bin_name = bin_name(ir, cfg);
    let pkg_name = format!("{bin_name}-cli");

    GenerationOutput {
        files: vec![
            OutputFile::text("Cargo.toml", emit_cargo_toml(&pkg_name, &bin_name)),
            OutputFile::text("src/main.rs", emit_main_rs(ir, cfg, &bin_name)),
            OutputFile::text("src/client.rs", emit_client_rs(ir)),
            OutputFile::text("src/runtime.rs", emit_runtime_rs()),
            OutputFile::text("README.md", emit_readme(ir, &bin_name)),
        ],
        diagnostics: vec![],
    }
}

fn bin_name(ir: &Ir, cfg: &Config) -> String {
    if let Some(n) = cfg.name.as_deref().filter(|s| !s.is_empty()) {
        return kebab_case(n);
    }
    let title = ir.info.title.trim();
    if title.is_empty() {
        "api-cli".into()
    } else {
        kebab_case(title)
    }
}

fn default_base_url(ir: &Ir, cfg: &Config) -> String {
    if let Some(u) = cfg.base_url.as_deref().filter(|s| !s.is_empty()) {
        return u.to_string();
    }
    ir.servers
        .first()
        .map(|s| s.url.clone())
        .unwrap_or_else(|| "http://localhost".into())
}

fn env_prefix(bin_name: &str) -> String {
    screaming_snake(bin_name)
}

// ---------------------------------------------------------------------------
// Cargo.toml
// ---------------------------------------------------------------------------

fn emit_cargo_toml(pkg_name: &str, bin_name: &str) -> String {
    format!(
        r#"# Generated by openapi-forge / generator-rust-clap.
[package]
name = "{pkg_name}"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "{bin_name}"
path = "src/main.rs"

[dependencies]
clap = {{ version = "4", features = ["derive", "env"] }}
tokio = {{ version = "1", features = ["macros", "rt-multi-thread"] }}
serde = {{ version = "1", features = ["derive"] }}
serde_json = "1"
anyhow = "1"
reqwest = {{ version = "0.12", default-features = false, features = ["json", "rustls-tls"] }}
urlencoding = "2"
"#
    )
}

// ---------------------------------------------------------------------------
// src/main.rs
// ---------------------------------------------------------------------------

fn emit_main_rs(ir: &Ir, cfg: &Config, bin_name: &str) -> String {
    let title = escape_rust_string(&ir.info.title);
    let version = escape_rust_string(&ir.info.version);
    let base_url = escape_rust_string(&default_base_url(ir, cfg));
    let prefix = env_prefix(bin_name);

    let mut out = String::new();
    out.push_str("// Generated by openapi-forge / generator-rust-clap; do not edit by hand.\n#![allow(clippy::needless_late_init, clippy::redundant_field_names)]\n\nmod client;\nmod runtime;\n\nuse clap::{Parser, Subcommand};\nuse client::ApiClient;\nuse runtime::OutputMode;\n\n");

    out.push_str(&format!(
        "#[derive(Parser)]\n#[command(name = \"{bin_name}\", version = \"{version}\", about = \"{title}\", long_about = None)]\nstruct Cli {{\n    /// API base URL.\n    #[arg(long, global = true, env = \"{prefix}_BASE_URL\", default_value = \"{base_url}\")]\n    base_url: String,\n\n    /// Bearer token for `Authorization: Bearer ...` requests.\n    #[arg(long, global = true, env = \"{prefix}_TOKEN\")]\n    token: Option<String>,\n\n    /// Output mode for response bodies.\n    #[arg(long, global = true, value_enum, default_value_t = OutputMode::Json)]\n    output: OutputMode,\n\n    #[command(subcommand)]\n    cmd: Cmd,\n}}\n\n"
    ));

    if ir.operations.is_empty() {
        out.push_str("#[derive(Subcommand)]\nenum Cmd {\n    /// (No operations declared in the spec.)\n    #[command(hide = true)]\n    Noop,\n}\n\n");
    } else {
        out.push_str("#[derive(Subcommand)]\nenum Cmd {\n");
        for op in &ir.operations {
            out.push_str(&render_variant(op));
        }
        out.push_str("}\n\n");
    }

    out.push_str("#[tokio::main(flavor = \"multi_thread\")]\nasync fn main() -> anyhow::Result<()> {\n    let cli = Cli::parse();\n    let client = ApiClient::new(cli.base_url, cli.token)?;\n    let result: serde_json::Value = match cli.cmd {\n");
    if ir.operations.is_empty() {
        out.push_str("        Cmd::Noop => return Ok(()),\n");
    } else {
        for op in &ir.operations {
            out.push_str(&render_match_arm(op));
        }
    }
    out.push_str("    };\n    runtime::print_output(&result, cli.output)\n}\n");

    out
}

fn render_variant(op: &Operation) -> String {
    let variant = pascal_case(&op.id);
    let summary = first_line(op.documentation.as_deref()).unwrap_or_default();
    let mut s = String::new();
    if !summary.is_empty() {
        s.push_str(&format!("    /// {}\n", escape_doc(&summary)));
    }

    let fields = collect_fields(op);
    if fields.is_empty() {
        s.push_str(&format!("    {variant},\n"));
    } else {
        s.push_str(&format!("    {variant} {{\n"));
        for f in &fields {
            if let Some(doc) = &f.doc {
                s.push_str(&format!("        /// {}\n", escape_doc(doc)));
            }
            for attr in &f.attrs {
                s.push_str(&format!("        {attr}\n"));
            }
            s.push_str(&format!("        {}: {},\n", f.ident, f.ty));
        }
        s.push_str("    },\n");
    }
    s
}

fn render_match_arm(op: &Operation) -> String {
    let variant = pascal_case(&op.id);
    let method_ident = snake_case(&op.id);
    let fields = collect_fields(op);
    let mut s = String::new();
    if fields.is_empty() {
        s.push_str(&format!(
            "        Cmd::{variant} => client.{method_ident}().await?,\n",
        ));
    } else {
        let names: Vec<&str> = fields.iter().map(|f| f.ident.as_str()).collect();
        s.push_str(&format!(
            "        Cmd::{variant} {{ {} }} => client.{method_ident}({}).await?,\n",
            names.join(", "),
            names.join(", "),
        ));
    }
    s
}

struct Field {
    ident: String,
    ty: String,
    doc: Option<String>,
    attrs: Vec<String>,
}

fn collect_fields(op: &Operation) -> Vec<Field> {
    let mut out = Vec::new();
    for p in &op.path_params {
        out.push(field_for_param(p, FieldKind::Positional));
    }
    for p in &op.query_params {
        out.push(field_for_param(p, FieldKind::Flag));
    }
    for p in &op.header_params {
        out.push(field_for_param(p, FieldKind::Flag));
    }
    for p in &op.cookie_params {
        out.push(field_for_param(p, FieldKind::Flag));
    }
    if let Some(body) = &op.request_body {
        out.push(field_for_body(body));
    }
    out
}

#[derive(Copy, Clone)]
enum FieldKind {
    Positional,
    Flag,
}

fn field_for_param(p: &Parameter, kind: FieldKind) -> Field {
    let ident = snake_case(&p.name);
    let (ty, attrs) = match (kind, p.required) {
        (FieldKind::Positional, _) => ("String".to_string(), vec![]),
        (FieldKind::Flag, true) => (
            "String".to_string(),
            vec![format!("#[arg(long = \"{}\")]", kebab_case(&p.name))],
        ),
        (FieldKind::Flag, false) => (
            "Option<String>".to_string(),
            vec![format!("#[arg(long = \"{}\")]", kebab_case(&p.name))],
        ),
    };
    let doc = first_line(p.documentation.as_deref());
    Field { ident, ty, doc, attrs }
}

fn field_for_body(body: &Body) -> Field {
    let ty = if body.required { "String" } else { "Option<String>" };
    Field {
        ident: "body".into(),
        ty: ty.into(),
        doc: Some("Request body: inline JSON, @file.json, or - for stdin.".into()),
        attrs: vec!["#[arg(long = \"body\")]".into()],
    }
}

// ---------------------------------------------------------------------------
// src/client.rs
// ---------------------------------------------------------------------------

fn emit_client_rs(ir: &Ir) -> String {
    let mut out = String::new();
    out.push_str("// Generated by openapi-forge / generator-rust-clap; do not edit by hand.\n#![allow(clippy::too_many_arguments, clippy::needless_borrow)]\n\nuse anyhow::{anyhow, Context, Result};\nuse serde_json::Value;\n\nuse crate::runtime::parse_body_arg;\n\npub struct ApiClient {\n    http: reqwest::Client,\n    base_url: String,\n    token: Option<String>,\n}\n\nimpl ApiClient {\n    pub fn new(base_url: String, token: Option<String>) -> Result<Self> {\n        Ok(Self {\n            http: reqwest::Client::builder().build()?,\n            base_url: base_url.trim_end_matches('/').to_string(),\n            token,\n        })\n    }\n\n    fn req(&self, method: reqwest::Method, path: &str) -> reqwest::RequestBuilder {\n        let mut b = self.http.request(method, format!(\"{}{}\", self.base_url, path));\n        if let Some(t) = &self.token { b = b.bearer_auth(t); }\n        b\n    }\n\n");

    for op in &ir.operations {
        out.push_str(&render_client_method(op));
    }

    out.push_str("}\n");
    out
}

fn render_client_method(op: &Operation) -> String {
    let method_ident = snake_case(&op.id);
    let http_method = method_path(&op.method);
    let path_template = &op.path_template;

    let mut sig_args = Vec::new();
    for p in &op.path_params {
        sig_args.push(format!("{}: String", snake_case(&p.name)));
    }
    for p in &op.query_params {
        let ident = snake_case(&p.name);
        let ty = if p.required { "String" } else { "Option<String>" };
        sig_args.push(format!("{ident}: {ty}"));
    }
    for p in &op.header_params {
        let ident = snake_case(&p.name);
        let ty = if p.required { "String" } else { "Option<String>" };
        sig_args.push(format!("{ident}: {ty}"));
    }
    for p in &op.cookie_params {
        let ident = snake_case(&p.name);
        let ty = if p.required { "String" } else { "Option<String>" };
        sig_args.push(format!("{ident}: {ty}"));
    }
    if let Some(body) = &op.request_body {
        let ty = if body.required { "String" } else { "Option<String>" };
        sig_args.push(format!("body: {ty}"));
    }
    let sig = sig_args.join(", ");

    let mut body = String::new();

    // Path interpolation. `{petId}` → `{}` in format!, with the corresponding ident.
    let (path_fmt, path_args) = render_path_interpolation(path_template, &op.path_params);
    if path_args.is_empty() {
        body.push_str(&format!("        let __path = String::from(\"{}\");\n", escape_rust_string(&path_fmt)));
    } else {
        body.push_str(&format!(
            "        let __path = format!(\"{}\", {});\n",
            escape_rust_string(&path_fmt),
            path_args.join(", "),
        ));
    }
    body.push_str(&format!(
        "        let mut __r = self.req({http_method}, &__path);\n"
    ));

    // Query params.
    for p in &op.query_params {
        let ident = snake_case(&p.name);
        let raw = &p.name;
        if p.required {
            body.push_str(&format!(
                "        __r = __r.query(&[(\"{raw}\", &{ident})]);\n"
            ));
        } else {
            body.push_str(&format!(
                "        if let Some(v) = &{ident} {{ __r = __r.query(&[(\"{raw}\", v)]); }}\n"
            ));
        }
    }
    // Header params.
    for p in &op.header_params {
        let ident = snake_case(&p.name);
        let raw = &p.name;
        if p.required {
            body.push_str(&format!(
                "        __r = __r.header(\"{raw}\", &{ident});\n"
            ));
        } else {
            body.push_str(&format!(
                "        if let Some(v) = &{ident} {{ __r = __r.header(\"{raw}\", v); }}\n"
            ));
        }
    }
    // Cookie params (combine into one Cookie header).
    if !op.cookie_params.is_empty() {
        body.push_str("        let mut __cookies: Vec<String> = Vec::new();\n");
        for p in &op.cookie_params {
            let ident = snake_case(&p.name);
            let raw = &p.name;
            if p.required {
                body.push_str(&format!(
                    "        __cookies.push(format!(\"{raw}={{}}\", urlencoding::encode(&{ident})));\n"
                ));
            } else {
                body.push_str(&format!(
                    "        if let Some(v) = &{ident} {{ __cookies.push(format!(\"{raw}={{}}\", urlencoding::encode(v))); }}\n"
                ));
            }
        }
        body.push_str("        if !__cookies.is_empty() { __r = __r.header(\"Cookie\", __cookies.join(\"; \")); }\n");
    }
    // Body.
    if let Some(b) = &op.request_body {
        if b.required {
            body.push_str("        let __body_value = parse_body_arg(&body).context(\"--body\")?;\n");
            body.push_str("        __r = __r.json(&__body_value);\n");
        } else {
            body.push_str("        if let Some(s) = &body {\n            let v = parse_body_arg(s).context(\"--body\")?;\n            __r = __r.json(&v);\n        }\n");
        }
    }

    body.push_str("        let __resp = __r.send().await.context(\"sending request\")?;\n");
    body.push_str("        let __status = __resp.status();\n");
    body.push_str("        let __text = __resp.text().await.context(\"reading response\")?;\n");
    body.push_str("        let __json: Value = if __text.is_empty() { Value::Null } else { serde_json::from_str(&__text).unwrap_or(Value::String(__text.clone())) };\n");
    body.push_str("        if !__status.is_success() {\n            return Err(anyhow!(\"HTTP {}: {}\", __status, __json));\n        }\n");
    body.push_str("        Ok(__json)\n");

    let mut s = String::new();
    if let Some(doc) = first_line(op.documentation.as_deref()) {
        s.push_str(&format!("    /// {}\n", escape_doc(&doc)));
    }
    s.push_str(&format!("    pub async fn {method_ident}(&self, {sig}) -> Result<Value> {{\n"));
    s.push_str(&body);
    s.push_str("    }\n\n");
    s
}

fn method_path(m: &HttpMethod) -> &'static str {
    match m {
        HttpMethod::Get => "reqwest::Method::GET",
        HttpMethod::Post => "reqwest::Method::POST",
        HttpMethod::Put => "reqwest::Method::PUT",
        HttpMethod::Delete => "reqwest::Method::DELETE",
        HttpMethod::Patch => "reqwest::Method::PATCH",
        HttpMethod::Options => "reqwest::Method::OPTIONS",
        HttpMethod::Head => "reqwest::Method::HEAD",
        HttpMethod::Trace => "reqwest::Method::TRACE",
        HttpMethod::Other(_) => "reqwest::Method::GET",
    }
}

/// Translate `/pets/{petId}/photos/{photoId}` into a `format!` template
/// `"/pets/{}/photos/{}"` and a list of argument expressions in the
/// same order: `[urlencoding::encode(&pet_id), urlencoding::encode(&photo_id)]`.
fn render_path_interpolation(template: &str, path_params: &[Parameter]) -> (String, Vec<String>) {
    let mut out_template = String::with_capacity(template.len());
    let mut args = Vec::new();
    let mut chars = template.chars().peekable();
    while let Some(c) = chars.next() {
        if c == '{' {
            let mut name = String::new();
            for c2 in chars.by_ref() {
                if c2 == '}' {
                    break;
                }
                name.push(c2);
            }
            let ident = snake_case(&name);
            // Confirm the name is a declared path param; if not, leave a literal.
            if path_params.iter().any(|p| snake_case(&p.name) == ident) {
                out_template.push_str("{}");
                args.push(format!("urlencoding::encode(&{ident})"));
            } else {
                out_template.push('{');
                out_template.push_str(&name);
                out_template.push('}');
            }
        } else if c == '}' {
            out_template.push('}');
        } else {
            out_template.push(c);
        }
    }
    (out_template, args)
}

// ---------------------------------------------------------------------------
// src/runtime.rs
// ---------------------------------------------------------------------------

fn emit_runtime_rs() -> String {
    r#"// Generated by openapi-forge / generator-rust-clap; do not edit by hand.
use anyhow::{Context, Result};
use serde_json::Value;
use std::io::Read;

pub fn parse_body_arg(s: &str) -> Result<Value> {
    if s == "-" {
        let mut buf = String::new();
        std::io::stdin().read_to_string(&mut buf).context("reading stdin")?;
        return serde_json::from_str(&buf).context("parsing stdin as JSON");
    }
    if let Some(path) = s.strip_prefix('@') {
        let buf = std::fs::read_to_string(path)
            .with_context(|| format!("reading file {path}"))?;
        return serde_json::from_str(&buf)
            .with_context(|| format!("parsing {path} as JSON"));
    }
    serde_json::from_str(s).context("parsing inline JSON")
}

#[derive(Copy, Clone, Debug, clap::ValueEnum)]
pub enum OutputMode {
    Json,
    Compact,
}

pub fn print_output(v: &Value, mode: OutputMode) -> Result<()> {
    if v.is_null() {
        return Ok(());
    }
    let s = match mode {
        OutputMode::Json => serde_json::to_string_pretty(v)?,
        OutputMode::Compact => serde_json::to_string(v)?,
    };
    println!("{s}");
    Ok(())
}
"#
    .into()
}

// ---------------------------------------------------------------------------
// README.md
// ---------------------------------------------------------------------------

fn emit_readme(ir: &Ir, bin_name: &str) -> String {
    format!(
        "# {bin}\n\nGenerated by openapi-forge / generator-rust-clap.\n\nSpec: {title} v{version}\n\nOperations: {n}\n\n## Build\n\n```sh\ncargo build --release\n```\n\n## Auth\n\nBearer token via `--token <jwt>` or the env var `{prefix}_TOKEN`.\n",
        bin = bin_name,
        title = ir.info.title,
        version = ir.info.version,
        n = ir.operations.len(),
        prefix = env_prefix(bin_name),
    )
}

fn first_line(s: Option<&str>) -> Option<String> {
    s.and_then(|s| s.lines().next()).map(|l| l.trim().to_string()).filter(|s| !s.is_empty())
}

fn escape_rust_string(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

fn escape_doc(s: &str) -> String {
    s.replace('\\', "\\\\").replace('\r', "")
}
